Models/ErrorViewModel.cs
using System;

namespace MonsterAdvancer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Monster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonsterAdvancer.Models
{
    public class Monster
    {
        public string Name { get; set; }
        public string Cr { get; set; }
        public string Xp { get; set; }
        public string Race { get; set; }
        public string Alignment { get; set; }
        public string Size { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public string Init { get; set; }
        public string Senses { get; set; }
        public string Aura { get; set; }
        public string AC { get; set; }
        public string AC_Mods { get; set; }
        public string HP { get; set; }
        public string HD { get; set; }
        public string HP_Mods { get; set; }
        public string Saves { get; set; }
        public string Fort { get; set; }
        public string Ref { get; set; }
        public string Will { get; set; }
        public string Save_Mods { get; set; }
        public string DefensiveAbilities { get; set; }
        public string DR { get; set; }
        public string Immune { get; set; }
        public string SR { get; set; }
        public string Weakness { get; set; }
        public string Speed { get; set; }
        public string Speed_Mod { get; set; }
        public string Melee { get; set; }
        public string Ranged { get; set; }
        public string Space { get; set; }
        public string Reach { get; set; }
        public string SpecialAttacks { get; set; }
        public string SpellLikeAbilities { get; set; }
        public string SpellsKnown { get; set; }
        public string SpellsPrepared { get; set; }
        public string SpellDomains { get; set; }
        public string AbilityScores { get; set; }
        public string AbilityScore_Mods { get; set; }
        public string BaseAtk { get; set; }
        public string CMB { get; set; }
        public string CMD { get; set; }
        public string Feats { get; set; }
        public string Skills { get; set; }
        public string RacialMods { get; set; }
        public string Languages { get; set; }
        public string SQ { get; set; }
        public string Environment { get; set; }
        public string Organization { get; set; }
        public string Treasure { get; set; }
        public string Description_Visual { get; set; }
        public string SpecialAbilities { get; set; }
        public string Description { get; set; }
        public string TemplatesApplied { get; set; }
    }
}

Models/MonsterArrayConverter.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonsterAdvancer.Models
{
    public class MonsterArrayConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return (objectType == typeof(Dictionary<string, JObject>));
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            JArray ja = JArray.Load(reader);
            var key = string.Empty;
            var dict = new Dictionary<string, JObject>();
            foreach (JObject item in ja)
            {
                key = item.Property("Name").Value.ToString();
                if (dict.ContainsKey(key))
                {
                    key = $"{key} ({item.Property("Source").Value})";
                    dict.Add(key, item);
                }
                else
                {
                    dict.Add(key, item);
                }
                
            }
            return dict;
        }

        public override bool CanWrite
        {
            get { return false; }
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }
}

Controllers/AdvancerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using MonsterAdvancer.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace MonsterAdvancer.Controllers
{
    public class AdvancerController : Controller
    {
        private readonly ILogger<AdvancerController> _logger;
        private Dictionary<string, JObject> _monsterDictionary;

        public AdvancerController(ILogger<AdvancerController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _monsterDictionary = GetMonsterList();
            ViewData["MonsterList"] = CreateDropDownList(_monsterDictionary);
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        private Dictionary<string, JObject> GetMonsterList()
        {
            using (StreamReader file = System.IO.File.OpenText(@"convertjson.json"))
            {
                return JsonConvert.DeserializeObject<Dictionary<string, JObject>>(file.ReadToEnd(), new MonsterArrayConverter());
            }
        }

        private List<SelectListItem> CreateDropDownList(Dictionary<string, JObject> monsters)
        {
            return monsters.Keys.Select(n => new SelectListItem
            {
                Value = n.ToString(),
                Text = n.ToString()
            }).ToList();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Advancer/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form name="form" onsubmit="return false;">
    <table border=0>
        <tbody>
            <tr>
                <td width="100%" colspan="2">
                    <table width="100%" border="0">
                        <tr>
                            <td>
                                <h3>Pathfinder Monster Advancer</h3>
                            </td>                         
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td height="100%" valign="top">
                    <table height="100%" border=0>
                        <tr height="5%">
                            <td valign="top">
                                <select name="MonsterChooser" style="width: 180">
                                    <option value='-1'>...</option>
                                </select>
                                <select asp-items="@((List<SelectListItem>)ViewData["MonsterList"])">
                                    <option value="">Pick one</option>
                                </select>
                            </td>
                        </tr>
                        <tr height="5%">
                            <td valign="bottom" align="center">
                                <input name="Go" type="button" value="Go" onClick="doIt();">
                                <input name="Reset" type="button" value="Reset" onClick="clearform();">
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <td><input name="Advanced" type="checkbox" onClick="cleanAdvanced(1);">Advanced&nbsp;&nbsp;</td>
                            <td><input name="VeryAdvanced" type="checkbox" onClick="cleanAdvanced(2);">Very Advanced&nbsp;&nbsp;</td>
                            <td><input name="ExtreemlyAdvanced" type="checkbox" onClick="cleanAdvanced(3);">Extremely Advanced&nbsp;&nbsp;</td>
                            <td><input name="ShowMultiple" type="checkbox" checked />Show Multiple</td>
                        </tr>
                        <tr>
                            <td><input name="Young" onClick="cleanYoung(1);" type="checkbox">Young</td>
                            <td><input name="VeryYoung" onClick="cleanYoung(2);" type="checkbox">Very Young</td>
                            <td><input name="ExtreemlyYoung" onClick="cleanYoung(3);" type="checkbox">Extreemly Young</td>
                            <td><input name="TwoColumn" type="checkbox" checked />Two Columns</td>
                        </tr>
                        <tr>
                            <td><input name="Giant" onClick="cleanGiant(1);" type="checkbox">Giant</td>
                            <td><input name="VeryGiant" onClick="cleanGiant(2);" type="checkbox">Very Giant</td>
                            <td><input name="ExtreemlyGiant" onClick="cleanGiant(3);" type="checkbox">Extreemly Giant</td>
                        </tr>
                        <tr>
                            <td><input name="Fiendish" onClick="cleanFeindish(1);" type="checkbox">Fiendish</td>
                            <td><input name="Celestial" onClick="cleanFeindish(2);" type="checkbox">Celestial</td>
                            <td>
                                <input name="Half_Dragon" type="checkbox">Half Dragon&nbsp;&nbsp;&nbsp;&nbsp;
                                <input name="Half_Fiend" type="checkbox">Half Fiend&nbsp;&nbsp;&nbsp;&nbsp;
                            </td>
                        </tr>
                        <tr>
                            <td><input name="Skeleton" type="checkbox" onclick="document.form.SkeletonBloody.checked=false;document.form.SkeletonBurning.checked=false;">Skeleton</td>
                            <td><input name="SkeletonBloody" type="checkbox" onclick="document.form.Skeleton.checked=false;document.form.SkeletonBurning.checked=false;">Bloody Skeleton</td>
                            <td><input name="SkeletonBurning" type="checkbox" onclick="document.form.Skeleton.checked=false;document.form.SkeletonBloody.checked=false;">Burning Skeleton</td>
                        </tr>
                        <tr>
                            <td><input name="Zombie" type="checkbox" onclick="document.form.ZombieFast.checked=false;document.form.ZombiePlague.checked=false;">Zombie</td>
                            <td><input name="ZombieFast" type="checkbox" onclick="document.form.Zombie.checked=false;document.form.ZombiePlague.checked=false;">Fast Zombie</td>
                            <td><input name="ZombiePlague" type="checkbox" onclick="document.form.Zombie.checked=false;document.form.ZombieFast.checked=false;">Plague Zombie</td>
                        </tr>
                        <tr>
                            <td colspan="2"><input name="AugmentSummoning" type="checkbox">Augment Summoning</td>
                            <td>
                                Add Racial Hit Dice: <input type="button" value="-" onclick="adjustRHD(-1);" />
                                <input name="RacialHitDice" type="text" size="1" value="0" maxlength="2" readonly style="text-align:center;" />
                                <input type="button" value="+" onclick="adjustRHD(1);" />
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    <table width="100%">
        <tbody>
            <tr>
                <td>
                    <table>
                        <div id="writeroot">
                            <div id="monsterDiv">&nbsp;</div>
                        </div>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonsterAdvancer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Advancer" asp-action="Index">MonsterAdvancer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advancer" asp-action="Index">Advancer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advancer" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MonsterAdvancer - <a asp-area="" asp-controller="Advancer" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>